## Setup e importaciones

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('./data/product_activity.csv')

print("Dataset cargado")
print(f"Shape: {df.shape}")

Dataset cargado
Shape: (8782, 12)

## Primera fotografia

In [ ]:
#ver primeras 3 filas
print("------Head------")
display(df.head(3))

#mostrar informacion general del dataset
print("\n------Info------")
df.info()

print("\n------Describe------")
display(df.describe())

------Head------

,user_id,created_at,country,plan_type,user_age,post_id,post_category,post_created_at,votes_received,user_total_posts,days_since_signup,device_type
0,U01988,2025-02-18T02:07:44,PY,pro,26.0,P0008515,sport,2025-05-07T20:55:28,7,16,78,mobile
1,U00236,2025-06-22T07:49:10,BR,free,27.0,P0001023,tech,2025-09-13T20:31:06,1,9,83,web
2,U00791,2024-02-12T02:45:45,CL,free,28.0,P0003405,tech,2024-02-14T05:17:48,11,2,2,mobile

------Info------
<class 'pandas.DataFrame'>
RangeIndex: 8782 entries, 0 to 8781
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            8782 non-null   str
 1   created_at         8782 non-null   str
 2   country            8782 non-null   str
 3   plan_type          8782 non-null   str
 4   user_age           8028 non-null   float64
 5   post_id            8782 non-null   str
 6   post_category      8782 non-null   str
 7   post_created_at    8782 non-null   str
 8   votes_received     8782 non-null   int64
 9   user_total_posts   8782 non-null   int64
 10  days_since_signup  8782 non-null   int64
 11  device_type        8782 non-null   str
dtypes: float64(1), int64(3), str(8)
memory usage: 823.4 KB

------Describe------

          user_age  votes_received  user_total_posts  days_since_signup
count  8028.000000     8782.000000       8782.000000        8782.000000
mean     27.902591        6.918356          8.324186          29.479390
std       7.547052        5.127311          6.754906          36.819928
min      16.000000        0.000000          1.000000           0.000000
25%      22.000000        3.000000          4.000000           5.000000
50%      28.000000        6.000000          6.000000          17.000000
75%      33.000000        9.000000         11.000000          40.000000
max      58.000000       74.000000         39.000000         404.000000